// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: xchange/isomessages/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a87ad235fe7f603a, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a87ad235fe7f603a, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetSecuritiesTradeConfirmationRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetSecuritiesTradeConfirmationRequest) Reset() {
	*m = QueryGetSecuritiesTradeConfirmationRequest{}
}
func (m *QueryGetSecuritiesTradeConfirmationRequest) String() string {
	return proto.CompactTextString(m)
}
func (*QueryGetSecuritiesTradeConfirmationRequest) ProtoMessage() {}
func (*QueryGetSecuritiesTradeConfirmationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a87ad235fe7f603a, []int{2}
}
func (m *QueryGetSecuritiesTradeConfirmationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSecuritiesTradeConfirmationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSecuritiesTradeConfirmationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSecuritiesTradeConfirmationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSecuritiesTradeConfirmationRequest.Merge(m, src)
}
func (m *QueryGetSecuritiesTradeConfirmationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSecuritiesTradeConfirmationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSecuritiesTradeConfirmationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSecuritiesTradeConfirmationRequest proto.InternalMessageInfo

func (m *QueryGetSecuritiesTradeConfirmationRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetSecuritiesTradeConfirmationResponse struct {
	SecuritiesTradeConfirmation SecuritiesTradeConfirmation `protobuf:"bytes,1,opt,name=SecuritiesTradeConfirmation,proto3" json:"SecuritiesTradeConfirmation"`
}

func (m *QueryGetSecuritiesTradeConfirmationResponse) Reset() {
	*m = QueryGetSecuritiesTradeConfirmationResponse{}
}
func (m *QueryGetSecuritiesTradeConfirmationResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryGetSecuritiesTradeConfirmationResponse) ProtoMessage() {}
func (*QueryGetSecuritiesTradeConfirmationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a87ad235fe7f603a, []int{3}
}
func (m *QueryGetSecuritiesTradeConfirmationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSecuritiesTradeConfirmationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSecuritiesTradeConfirmationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSecuritiesTradeConfirmationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSecuritiesTradeConfirmationResponse.Merge(m, src)
}
func (m *QueryGetSecuritiesTradeConfirmationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSecuritiesTradeConfirmationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSecuritiesTradeConfirmationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSecuritiesTradeConfirmationResponse proto.InternalMessageInfo

func (m *QueryGetSecuritiesTradeConfirmationResponse) GetSecuritiesTradeConfirmation() SecuritiesTradeConfirmation {
	if m != nil {
		return m.SecuritiesTradeConfirmation
	}
	return SecuritiesTradeConfirmation{}
}

type QueryAllSecuritiesTradeConfirmationRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSecuritiesTradeConfirmationRequest) Reset() {
	*m = QueryAllSecuritiesTradeConfirmationRequest{}
}
func (m *QueryAllSecuritiesTradeConfirmationRequest) String() string {
	return proto.CompactTextString(m)
}
func (*QueryAllSecuritiesTradeConfirmationRequest) ProtoMessage() {}
func (*QueryAllSecuritiesTradeConfirmationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a87ad235fe7f603a, []int{4}
}
func (m *QueryAllSecuritiesTradeConfirmationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSecuritiesTradeConfirmationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSecuritiesTradeConfirmationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSecuritiesTradeConfirmationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSecuritiesTradeConfirmationRequest.Merge(m, src)
}
func (m *QueryAllSecuritiesTradeConfirmationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSecuritiesTradeConfirmationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSecuritiesTradeConfirmationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSecuritiesTradeConfirmationRequest proto.InternalMessageInfo

func (m *QueryAllSecuritiesTradeConfirmationRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllSecuritiesTradeConfirmationResponse struct {
	SecuritiesTradeConfirmation []SecuritiesTradeConfirmation `protobuf:"bytes,1,rep,name=SecuritiesTradeConfirmation,proto3" json:"SecuritiesTradeConfirmation"`
	Pagination                  *query.PageResponse           `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSecuritiesTradeConfirmationResponse) Reset() {
	*m = QueryAllSecuritiesTradeConfirmationResponse{}
}
func (m *QueryAllSecuritiesTradeConfirmationResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryAllSecuritiesTradeConfirmationResponse) ProtoMessage() {}
func (*QueryAllSecuritiesTradeConfirmationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a87ad235fe7f603a, []int{5}
}
func (m *QueryAllSecuritiesTradeConfirmationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSecuritiesTradeConfirmationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSecuritiesTradeConfirmationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSecuritiesTradeConfirmationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSecuritiesTradeConfirmationResponse.Merge(m, src)
}
func (m *QueryAllSecuritiesTradeConfirmationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSecuritiesTradeConfirmationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSecuritiesTradeConfirmationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSecuritiesTradeConfirmationResponse proto.InternalMessageInfo

func (m *QueryAllSecuritiesTradeConfirmationResponse) GetSecuritiesTradeConfirmation() []SecuritiesTradeConfirmation {
	if m != nil {
		return m.SecuritiesTradeConfirmation
	}
	return nil
}

func (m *QueryAllSecuritiesTradeConfirmationResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "xchange.isomessages.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "xchange.isomessages.QueryParamsResponse")
	proto.RegisterType((*QueryGetSecuritiesTradeConfirmationRequest)(nil), "xchange.isomessages.QueryGetSecuritiesTradeConfirmationRequest")
	proto.RegisterType((*QueryGetSecuritiesTradeConfirmationResponse)(nil), "xchange.isomessages.QueryGetSecuritiesTradeConfirmationResponse")
	proto.RegisterType((*QueryAllSecuritiesTradeConfirmationRequest)(nil), "xchange.isomessages.QueryAllSecuritiesTradeConfirmationRequest")
	proto.RegisterType((*QueryAllSecuritiesTradeConfirmationResponse)(nil), "xchange.isomessages.QueryAllSecuritiesTradeConfirmationResponse")
}

func init() { proto.RegisterFile("xchange/isomessages/query.proto", fileDescriptor_a87ad235fe7f603a) }

var fileDescriptor_a87ad235fe7f603a = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcf, 0x6a, 0x13, 0x41,
	0x18, 0xcf, 0xc4, 0x98, 0xc3, 0x08, 0x1e, 0xa6, 0x3d, 0x48, 0xa2, 0xdb, 0xb2, 0x82, 0x2d, 0x15,
	0x66, 0x6c, 0x54, 0x4a, 0x45, 0xa8, 0xad, 0x60, 0xaf, 0x31, 0x7a, 0xf2, 0x52, 0x26, 0xc9, 0xe7,
	0x38, 0xb0, 0xd9, 0xd9, 0xee, 0x4c, 0x24, 0x45, 0x04, 0xf1, 0x09, 0x04, 0x1f, 0xc2, 0x57, 0xe9,
	0x31, 0xe0, 0xc5, 0x93, 0x7f, 0x12, 0x1f, 0xc0, 0x47, 0x90, 0xcc, 0x4c, 0x74, 0x83, 0xdb, 0xcd,
	0x56, 0xe8, 0x2d, 0x64, 0x7e, 0xdf, 0xef, 0xcf, 0xb7, 0xbf, 0x19, 0xbc, 0x36, 0xea, 0xbd, 0xe2,
	0xb1, 0x00, 0x26, 0xb5, 0x1a, 0x80, 0xd6, 0x5c, 0x80, 0x66, 0xc7, 0x43, 0x48, 0x4f, 0x68, 0x92,
	0x2a, 0xa3, 0xc8, 0x8a, 0x07, 0xd0, 0x0c, 0xa0, 0xb1, 0x2a, 0x94, 0x50, 0xf6, 0x9c, 0xcd, 0x7e,
	0x39, 0x68, 0xe3, 0xba, 0x50, 0x4a, 0x44, 0xc0, 0x78, 0x22, 0x19, 0x8f, 0x63, 0x65, 0xb8, 0x91,
	0x2a, 0xd6, 0xfe, 0x74, 0xab, 0xa7, 0xf4, 0x40, 0x69, 0xd6, 0xe5, 0x1a, 0x9c, 0x02, 0x7b, 0xbd,
	0xdd, 0x05, 0xc3, 0xb7, 0x59, 0xc2, 0x85, 0x8c, 0x2d, 0xd8, 0x63, 0xd7, 0xf3, 0x5c, 0x25, 0x3c,
	0xe5, 0x83, 0x39, 0xdb, 0x4e, 0x1e, 0x42, 0x43, 0x6f, 0x98, 0x4a, 0x23, 0x41, 0x1f, 0x99, 0x94,
	0xf7, 0xe1, 0xa8, 0xa7, 0xe2, 0x97, 0x32, 0x1d, 0x64, 0xa8, 0xc3, 0x55, 0x4c, 0x9e, 0xce, 0xc4,
	0xdb, 0x96, 0xad, 0x03, 0xc7, 0x43, 0xd0, 0x26, 0x6c, 0xe3, 0x95, 0x85, 0x7f, 0x75, 0xa2, 0x62,
	0x0d, 0x64, 0x17, 0xd7, 0x9d, 0xea, 0x35, 0xb4, 0x8e, 0x36, 0xaf, 0xb4, 0x9a, 0x34, 0x67, 0x1b,
	0xd4, 0x0d, 0x1d, 0xd4, 0x4e, 0xbf, 0xae, 0x55, 0x3a, 0x7e, 0x20, 0x7c, 0x88, 0xb7, 0x2c, 0xe3,
	0x21, 0x98, 0x67, 0x7f, 0x6c, 0x3d, 0x9f, 0xb9, 0x7a, 0x9c, 0x31, 0xe5, 0xf5, 0xc9, 0x55, 0x5c,
	0x95, 0x7d, 0x2b, 0x52, 0xeb, 0x54, 0x65, 0x3f, 0xfc, 0x84, 0xf0, 0xed, 0x52, 0xe3, 0xde, 0xe8,
	0x08, 0x37, 0x0b, 0x60, 0xde, 0xfd, 0x9d, 0x5c, 0xf7, 0x05, 0x73, 0x3e, 0x52, 0x11, 0x75, 0x68,
	0x7c, 0xce, 0xfd, 0x28, 0x2a, 0x91, 0xf3, 0x09, 0xc6, 0x7f, 0x3f, 0xb6, 0xb7, 0x75, 0x8b, 0xba,
	0x66, 0xd0, 0x59, 0x33, 0xa8, 0xeb, 0x9e, 0x6f, 0x06, 0x6d, 0x73, 0x01, 0x7e, 0xb6, 0x93, 0x99,
	0x0c, 0x7f, 0xcd, 0xf7, 0xb3, 0x4c, 0xb6, 0xec, 0x7e, 0x2e, 0x5d, 0xd0, 0x7e, 0xc8, 0xe1, 0x42,
	0xe2, 0xaa, 0x4d, 0xbc, 0xb1, 0x34, 0xb1, 0xb3, 0x9d, 0x8d, 0xdc, 0x1a, 0xd7, 0xf0, 0x65, 0x1b,
	0x99, 0xbc, 0x43, 0xb8, 0xee, 0x3a, 0x47, 0x36, 0x72, 0x2d, 0xff, 0x5b, 0xf0, 0xc6, 0xe6, 0x72,
	0xa0, 0xd3, 0x0c, 0x6f, 0xbe, 0xff, 0xfc, 0xf3, 0x63, 0xf5, 0x06, 0x69, 0xb2, 0xb3, 0x2f, 0x21,
	0xf9, 0x81, 0x0a, 0x17, 0x4a, 0xf6, 0xce, 0x96, 0x2b, 0x75, 0x21, 0x1a, 0x8f, 0xfe, 0x9f, 0xc0,
	0xe7, 0xd8, 0xb3, 0x39, 0x76, 0xc9, 0x0e, 0x3b, 0xf7, 0x53, 0xc1, 0xde, 0xc8, 0xfe, 0x5b, 0xf2,
	0x0d, 0xe1, 0xa0, 0x40, 0x68, 0x3f, 0x8a, 0x8a, 0x62, 0x96, 0xba, 0x0f, 0x45, 0x31, 0xcb, 0x35,
	0x3b, 0x7c, 0x60, 0x63, 0xde, 0x23, 0xad, 0xf3, 0xc7, 0x3c, 0xb8, 0x7f, 0x3a, 0x09, 0xd0, 0x78,
	0x12, 0xa0, 0xef, 0x93, 0x00, 0x7d, 0x98, 0x06, 0x95, 0xf1, 0x34, 0xa8, 0x7c, 0x99, 0x06, 0x95,
	0x17, 0xcd, 0x39, 0xd9, 0x68, 0x81, 0xce, 0x9c, 0x24, 0xa0, 0xbb, 0x75, 0xfb, 0x92, 0xde, 0xfd,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0x36, 0xd7, 0x82, 0x3b, 0x3c, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of SecuritiesTradeConfirmation items.
	SecuritiesTradeConfirmation(ctx context.Context, in *QueryGetSecuritiesTradeConfirmationRequest, opts ...grpc.CallOption) (*QueryGetSecuritiesTradeConfirmationResponse, error)
	SecuritiesTradeConfirmationAll(ctx context.Context, in *QueryAllSecuritiesTradeConfirmationRequest, opts ...grpc.CallOption) (*QueryAllSecuritiesTradeConfirmationResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/xchange.isomessages.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SecuritiesTradeConfirmation(ctx context.Context, in *QueryGetSecuritiesTradeConfirmationRequest, opts ...grpc.CallOption) (*QueryGetSecuritiesTradeConfirmationResponse, error) {
	out := new(QueryGetSecuritiesTradeConfirmationResponse)
	err := c.cc.Invoke(ctx, "/xchange.isomessages.Query/SecuritiesTradeConfirmation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SecuritiesTradeConfirmationAll(ctx context.Context, in *QueryAllSecuritiesTradeConfirmationRequest, opts ...grpc.CallOption) (*QueryAllSecuritiesTradeConfirmationResponse, error) {
	out := new(QueryAllSecuritiesTradeConfirmationResponse)
	err := c.cc.Invoke(ctx, "/xchange.isomessages.Query/SecuritiesTradeConfirmationAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of SecuritiesTradeConfirmation items.
	SecuritiesTradeConfirmation(context.Context, *QueryGetSecuritiesTradeConfirmationRequest) (*QueryGetSecuritiesTradeConfirmationResponse, error)
	SecuritiesTradeConfirmationAll(context.Context, *QueryAllSecuritiesTradeConfirmationRequest) (*QueryAllSecuritiesTradeConfirmationResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) SecuritiesTradeConfirmation(ctx context.Context, req *QueryGetSecuritiesTradeConfirmationRequest) (*QueryGetSecuritiesTradeConfirmationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SecuritiesTradeConfirmation not implemented")
}
func (*UnimplementedQueryServer) SecuritiesTradeConfirmationAll(ctx context.Context, req *QueryAllSecuritiesTradeConfirmationRequest) (*QueryAllSecuritiesTradeConfirmationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SecuritiesTradeConfirmationAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xchange.isomessages.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SecuritiesTradeConfirmation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSecuritiesTradeConfirmationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SecuritiesTradeConfirmation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xchange.isomessages.Query/SecuritiesTradeConfirmation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SecuritiesTradeConfirmation(ctx, req.(*QueryGetSecuritiesTradeConfirmationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SecuritiesTradeConfirmationAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllSecuritiesTradeConfirmationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SecuritiesTradeConfirmationAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xchange.isomessages.Query/SecuritiesTradeConfirmationAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SecuritiesTradeConfirmationAll(ctx, req.(*QueryAllSecuritiesTradeConfirmationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "xchange.isomessages.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "SecuritiesTradeConfirmation",
			Handler:    _Query_SecuritiesTradeConfirmation_Handler,
		},
		{
			MethodName: "SecuritiesTradeConfirmationAll",
			Handler:    _Query_SecuritiesTradeConfirmationAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xchange/isomessages/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetSecuritiesTradeConfirmationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSecuritiesTradeConfirmationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSecuritiesTradeConfirmationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSecuritiesTradeConfirmationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSecuritiesTradeConfirmationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSecuritiesTradeConfirmationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.SecuritiesTradeConfirmation.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllSecuritiesTradeConfirmationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSecuritiesTradeConfirmationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSecuritiesTradeConfirmationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllSecuritiesTradeConfirmationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSecuritiesTradeConfirmationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSecuritiesTradeConfirmationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.SecuritiesTradeConfirmation) > 0 {
		for iNdEx := len(m.SecuritiesTradeConfirmation) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SecuritiesTradeConfirmation[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetSecuritiesTradeConfirmationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetSecuritiesTradeConfirmationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SecuritiesTradeConfirmation.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllSecuritiesTradeConfirmationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllSecuritiesTradeConfirmationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.SecuritiesTradeConfirmation) > 0 {
		for _, e := range m.SecuritiesTradeConfirmation {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSecuritiesTradeConfirmationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSecuritiesTradeConfirmationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSecuritiesTradeConfirmationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSecuritiesTradeConfirmationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSecuritiesTradeConfirmationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSecuritiesTradeConfirmationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecuritiesTradeConfirmation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SecuritiesTradeConfirmation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSecuritiesTradeConfirmationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSecuritiesTradeConfirmationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSecuritiesTradeConfirmationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSecuritiesTradeConfirmationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSecuritiesTradeConfirmationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSecuritiesTradeConfirmationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecuritiesTradeConfirmation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecuritiesTradeConfirmation = append(m.SecuritiesTradeConfirmation, SecuritiesTradeConfirmation{})
			if err := m.SecuritiesTradeConfirmation[len(m.SecuritiesTradeConfirmation)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
