// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: xchange/isomessages/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgParseSecTrade struct {
	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	TradConfId     string `protobuf:"bytes,2,opt,name=tradConfId,proto3" json:"tradConfId,omitempty"`
	TradConfDtTm   string `protobuf:"bytes,3,opt,name=tradConfDtTm,proto3" json:"tradConfDtTm,omitempty"`
	RltdOrdrId     string `protobuf:"bytes,4,opt,name=rltdOrdrId,proto3" json:"rltdOrdrId,omitempty"`
	RltdCshMvmntId string `protobuf:"bytes,5,opt,name=rltdCshMvmntId,proto3" json:"rltdCshMvmntId,omitempty"`
}

func (m *MsgParseSecTrade) Reset()         { *m = MsgParseSecTrade{} }
func (m *MsgParseSecTrade) String() string { return proto.CompactTextString(m) }
func (*MsgParseSecTrade) ProtoMessage()    {}
func (*MsgParseSecTrade) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeeea409ff504b1c, []int{0}
}
func (m *MsgParseSecTrade) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgParseSecTrade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgParseSecTrade.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgParseSecTrade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgParseSecTrade.Merge(m, src)
}
func (m *MsgParseSecTrade) XXX_Size() int {
	return m.Size()
}
func (m *MsgParseSecTrade) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgParseSecTrade.DiscardUnknown(m)
}

var xxx_messageInfo_MsgParseSecTrade proto.InternalMessageInfo

func (m *MsgParseSecTrade) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgParseSecTrade) GetTradConfId() string {
	if m != nil {
		return m.TradConfId
	}
	return ""
}

func (m *MsgParseSecTrade) GetTradConfDtTm() string {
	if m != nil {
		return m.TradConfDtTm
	}
	return ""
}

func (m *MsgParseSecTrade) GetRltdOrdrId() string {
	if m != nil {
		return m.RltdOrdrId
	}
	return ""
}

func (m *MsgParseSecTrade) GetRltdCshMvmntId() string {
	if m != nil {
		return m.RltdCshMvmntId
	}
	return ""
}

type MsgParseSecTradeResponse struct {
}

func (m *MsgParseSecTradeResponse) Reset()         { *m = MsgParseSecTradeResponse{} }
func (m *MsgParseSecTradeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgParseSecTradeResponse) ProtoMessage()    {}
func (*MsgParseSecTradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeeea409ff504b1c, []int{1}
}
func (m *MsgParseSecTradeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgParseSecTradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgParseSecTradeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgParseSecTradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgParseSecTradeResponse.Merge(m, src)
}
func (m *MsgParseSecTradeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgParseSecTradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgParseSecTradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgParseSecTradeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgParseSecTrade)(nil), "xchange.isomessages.MsgParseSecTrade")
	proto.RegisterType((*MsgParseSecTradeResponse)(nil), "xchange.isomessages.MsgParseSecTradeResponse")
}

func init() { proto.RegisterFile("xchange/isomessages/tx.proto", fileDescriptor_aeeea409ff504b1c) }

var fileDescriptor_aeeea409ff504b1c = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xa9, 0x48, 0xce, 0x48,
	0xcc, 0x4b, 0x4f, 0xd5, 0xcf, 0x2c, 0xce, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0xd6,
	0x2f, 0xa9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x86, 0xca, 0xea, 0x21, 0xc9, 0x2a,
	0xed, 0x60, 0xe4, 0x12, 0xf0, 0x2d, 0x4e, 0x0f, 0x48, 0x2c, 0x2a, 0x4e, 0x0d, 0x4e, 0x4d, 0x0e,
	0x29, 0x4a, 0x4c, 0x49, 0x15, 0x92, 0xe0, 0x62, 0x4f, 0x2e, 0x4a, 0x4d, 0x2c, 0xc9, 0x2f, 0x92,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x85, 0xe4, 0xb8, 0xb8, 0x4a, 0x8a, 0x12, 0x53,
	0x9c, 0xf3, 0xf3, 0xd2, 0x3c, 0x53, 0x24, 0x98, 0xc0, 0x92, 0x48, 0x22, 0x42, 0x4a, 0x5c, 0x3c,
	0x30, 0x9e, 0x4b, 0x49, 0x48, 0xae, 0x04, 0x33, 0x58, 0x05, 0x8a, 0x18, 0xc8, 0x8c, 0xa2, 0x9c,
	0x92, 0x14, 0xff, 0xa2, 0x94, 0x22, 0xcf, 0x14, 0x09, 0x16, 0x88, 0x19, 0x08, 0x11, 0x21, 0x35,
	0x2e, 0x3e, 0x10, 0xcf, 0xb9, 0x38, 0xc3, 0xb7, 0x2c, 0x37, 0xaf, 0xc4, 0x33, 0x45, 0x82, 0x15,
	0xac, 0x06, 0x4d, 0x54, 0x49, 0x8a, 0x4b, 0x02, 0xdd, 0xe5, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79,
	0xc5, 0xa9, 0x46, 0x39, 0x5c, 0xcc, 0xbe, 0xc5, 0xe9, 0x42, 0xa9, 0x5c, 0xbc, 0xa8, 0x3e, 0x53,
	0xd5, 0xc3, 0x12, 0x08, 0x7a, 0xe8, 0xc6, 0x48, 0xe9, 0x12, 0xa5, 0x0c, 0x66, 0x9b, 0x93, 0xe9,
	0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1, 0x1c,
	0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0x49, 0xc3, 0x62, 0xa4, 0x02, 0x35,
	0x4e, 0x2a, 0x0b, 0x52, 0x8b, 0x93, 0xd8, 0xc0, 0xf1, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0x07, 0xde, 0x83, 0xca, 0xb7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	ParseSecTrade(ctx context.Context, in *MsgParseSecTrade, opts ...grpc.CallOption) (*MsgParseSecTradeResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ParseSecTrade(ctx context.Context, in *MsgParseSecTrade, opts ...grpc.CallOption) (*MsgParseSecTradeResponse, error) {
	out := new(MsgParseSecTradeResponse)
	err := c.cc.Invoke(ctx, "/xchange.isomessages.Msg/ParseSecTrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	ParseSecTrade(context.Context, *MsgParseSecTrade) (*MsgParseSecTradeResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ParseSecTrade(ctx context.Context, req *MsgParseSecTrade) (*MsgParseSecTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseSecTrade not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ParseSecTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgParseSecTrade)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ParseSecTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xchange.isomessages.Msg/ParseSecTrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ParseSecTrade(ctx, req.(*MsgParseSecTrade))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "xchange.isomessages.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseSecTrade",
			Handler:    _Msg_ParseSecTrade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xchange/isomessages/tx.proto",
}

func (m *MsgParseSecTrade) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgParseSecTrade) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgParseSecTrade) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RltdCshMvmntId) > 0 {
		i -= len(m.RltdCshMvmntId)
		copy(dAtA[i:], m.RltdCshMvmntId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RltdCshMvmntId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.RltdOrdrId) > 0 {
		i -= len(m.RltdOrdrId)
		copy(dAtA[i:], m.RltdOrdrId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RltdOrdrId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TradConfDtTm) > 0 {
		i -= len(m.TradConfDtTm)
		copy(dAtA[i:], m.TradConfDtTm)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TradConfDtTm)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TradConfId) > 0 {
		i -= len(m.TradConfId)
		copy(dAtA[i:], m.TradConfId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TradConfId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgParseSecTradeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgParseSecTradeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgParseSecTradeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgParseSecTrade) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TradConfId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TradConfDtTm)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RltdOrdrId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RltdCshMvmntId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgParseSecTradeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgParseSecTrade) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgParseSecTrade: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgParseSecTrade: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradConfId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TradConfId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradConfDtTm", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TradConfDtTm = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RltdOrdrId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RltdOrdrId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RltdCshMvmntId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RltdCshMvmntId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgParseSecTradeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgParseSecTradeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgParseSecTradeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
